### PR TITLE
Covid cases and vaccines

### PR DESCRIPTION
**Pull request by MaryLvV**
This may be too open-ended and I probably need to add a caution about drawing conclusions based on partial data, but have this at a point where I would love feedback/suggestions.

I had some correspondence yesterday with Rand Carpenter. He updated the vaccination data to reflect first or second dose, but there's no way currently to tell whether a single-dose or two-dose vaccine was administered. He said:   

```We’re pulling this from the state vaccination information system, and surely there’s a way. We have an interest in knowing when a person is fully or partially vaccinated. I’ll talk to the COVID staff next week. What is your objective with these numbers? That might help me when talking to them.```   

and my response was:   

```Students will be looking at where cases occurred and where people are getting vaccinated alongside Census data for education level, age, income, race/ethnicity to see if there are any discernible patterns for groups more likely to contract the virus and those more likely to get vaccinated. I’m very open to anything else you think would be interesting/valuable for them to investigate.```

### CODE REVIEW

**Review by tfwhitesell — COMMENTED** [review]
Do they have a dataset with vaccination site details? Having the date, vaccination location zip code, how many doses, and which vaccine was administered would be helpful to cross-reference with the dose number. It's really only an issue once the J&J vaccine started being administered. I would be interested to know at least how many of each vaccine are being administered citywide in order to determine the effect of the single-dose vaccine on dose count.

**Comment by MaryLvV** [comment]
Let's see what Dr. Carpenter comes back with after talking to the state folks. I'm not sure if the site data is available or not. I agree the biggest thing now is whether folks are fully (or just partially) vaccinated.

**Comment by raom1** [comment]
This seems like a really interesting project. One thing to note for the PR, it looks like some of the commit history from the Socrata API project is part of this PR commit history. It may be good to pull master into this branch before merging the PR.

**Comment by MaryLvV** [comment]
Please take a look at this. After lots of back and forth, and a little work on my part, we can tell whether a vaccine given is Johnson & Johnson or Pfizer/Moderna. Is the README clear?

**Pull request merged**
