### PR TITLE
add toolbox notebook

### PR DESCRIPTION
**Pull request by cattfield**
added toolbox notebook

### CODE REVIEW

**Comment by MaryLvV** [comment]
The 3rd sound link (`mischievous`)is broken @cattfield. You could sub this one (https://www.talkingwav.com/wp-content/uploads/2017/10/mario_09.wav) or find your own.

**Comment by cattfield** [comment]
Nice find, Mary! updated the mischievous sound with the mario audio.

**Comment by MaryLvV** [comment]
LGTM @cattfield

**Review by raom1 — APPROVED** [review]
Let's get that money

**Pull request merged**
