### PR TITLE
Socrata api project

### PR DESCRIPTION
**Pull request by raom1**

### CODE REVIEW

**Review by amarsee — APPROVED** [review]

**Review by tfwhitesell — APPROVED** [review]

**Comment by mcvholloway** [comment]
Really nice project! 
I have a couple of questions.
1. First, what do you think about linking directly to the Top 500 searches page and 311 Service requests pages when they are referred to in the directions?
2. Are we wanting them to use json (the default when they click on the API button), or should we point out that they probably want to switch that to csv? That's something they would _probably_ notice on their own, but I know that students can get tunnel vision sometimes.
3. Is the intention for them to use requests or use the sodapy package (or student's choice)?
4. This could be because I was doing something wrong, but I got thrown off by the statement in number 5 that "The full data set is too big for a single request so you will need to combine the output from multiple requests". I set the limit on that one to 1000000 and was able to get everything in one go. That's the same thing that I did on the first question about getting all of the Top 500 monthly searches, so that made me question if I had done number 1 incorrectly or in a different way than intended.

**Comment by raom1** [comment]
Thanks @mcvholloway!

1. Yes, I think that would be a good idea, I'll add the links for each of those things. No need to add unnecessary complexity, they have enough with the APIs.
2. I was expecting use JSON for everything. Some files have XML format that I know @MaryLvV mentioned, but the Top 500 and 311 Service Requests don't have that as an option. I can add something in the top paragraph to make sure they use JSON when getting the endpoints.
3. I was intending them to use `requests` and the reason is because that exposes the functional parts of the API more and also its more translatable to other APIs, especially since not every API will have a python wrapper for it
4. That's really interesting, the documentation indicates that there is a max number of rows you can pull back in a single request: ```For performance, SODA APIs are paged, and return a maximum of 50,000 records per page. So, to request subsequent pages, you’ll need to use the $limit and $offset parameters to request more data.```. The intention of that question was, again, to dig into the documentation and to get experience with at least one version of paginated data. I guess if they think to try a much higher limit they can do that but if they read the documentation hopefully they will try using the pagination.

**Comment by mcvholloway** [comment]
Oh, I see, @raom1. It looks like they say [here](https://dev.socrata.com/docs/paging.html) that the 50,000 max limit is removed for SODA 2.1 APIs, which explains why I was able to get all of them.

**Review by mcvholloway — APPROVED** [review]

**Comment by raom1** [comment]
Oh good find @mcvholloway! Thanks, that makes a lot of sense. I can leave it in there to try and get them to paginate the data but if they do what you did then thats fine.

**Comment by raom1** [comment]
Added some changes based on @mcvholloway's comments and experience from DDA3.
- Added links to Top 500 and 311 Requests data sets
- Indicate they should stick with `JSON` format for the output
- Indicate they should use the `requests` package
- Modify the hint to just encourage them to check how many rows can be pulled back in a single request. If they see they can use a single request with a high `$limit` that is fine since they are reading the documentation, otherwise they will build a for loop, which is also good practice
- Reorganized questions since the previous first question was somewhat challenging to get the data formatted correctly. @cattfield also mentioned that one of the later questions helped understand the initial question
- Added other hyperlinked text instead of putting the links separate
- Separated the questions into `Questions` (1-4), `Stretch questions` (5-6), and `Bonus` (last one). This is because DDA3 was having a hard time working through the initial questions and I ended up saying that the first 4 were important and the remaining were nice to have
- Add additional note that they will have to break the examples in the documentation to the `url` and `params` for the `requests.get` function
- Added a `Show and Tell` section to do some expectation setting for what the presentations will look like. If anyone things I missed the mark on this please say so and I'll change it

**Review by MaryLvV — APPROVED** [review]

**Pull request merged**
